import asyncio
import aiohttp
from db import Connection
from network import Async
from .task import Task
import time
import datetime
import sys
from log import logger


class GuildTagTask(Task):
    def __init__(self, start_after, sleep):
        super().__init__(start_after, sleep)
        
    def stop(self):
        self.finished = True
        self.continuous_task.cancel()

    def run(self):
        self.finished = False
        async def guild_tag_task():
            await asyncio.sleep(self.start_after)
            
            while not self.finished:
                # this entire routine will take like 10MB/beat
                logger.info("GUILD TAG NAME TASK START")
                start = time.time()

                updated_guilds = set([x for x in await Async.get("https://api.wynncraft.com/v3/guild/list/guild")]) # like 200K mem max
                res = Connection.execute("SELECT guild FROM guild_tag_name")
                current_guilds = set(x[0] for x in res)
                current_guilds_lower = {x.lower().strip() for x in current_guilds}
                
                difference_dupe = updated_guilds-current_guilds
                difference = {x for x in difference_dupe if not x.lower().strip() in current_guilds_lower}

                logger.info(f"GUILD TAG NAME TASK: (difference: {len(difference)})")

                inserts = []
                logger.info(f"{difference}")
                for newg in difference:
                    if newg == "" or "(AutoGenerated)" in newg:
                        continue
                    
                    req = await Async.get("https://api.wynncraft.com/v3/guild/"+newg)
                    if not isinstance(req, dict):
                        logger.warn(f"Skipping guild with bad response: {newg}")
                        continue

                    tag = req.get("prefix")
                    if not tag:
                        logger.warn(f"Skipping guild without prefix: {newg}")
                        continue
                    
                    current_guild_members = set()
                    for rank in req["members"]:
                        if type(req["members"][rank]) != dict: continue
                        current_guild_members |= req["members"][rank].keys()

                    n_members = len(current_guild_members)
                    inserts.append(f"('{newg}','{tag}',{n_members})")
                    await asyncio.sleep(0.3)

                # batch insert if the # is too long for some reason
                for i in range(0, len(inserts), 50):
                    batch = inserts[i:min(i+50, len(inserts))]
                    Connection.execute("REPLACE INTO guild_tag_name VALUES "+','.join(batch))

                end = time.time()
                logger.info("GUILD TAG NAME TASK"+f" {end-start}s")
                
                await asyncio.sleep(self.sleep)
        
            logger.info("GuildTagTask finished")
        self.continuous_task = asyncio.get_event_loop().create_task(self.continuously(guild_tag_task))
